server.port=9090

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App properties for JWT
app.jwtCookieName=bezkoder
app.jwtSecret=KmZeV9OK6Ey74UNmARySOCGJx+yyi7qSODOkl78zW3AHuWMSShnfcf37Wk1Gl/EKvhsFvXjHX/z8dXg0AHjiLw==
app.jwtExpirationMs=86400000
